#!/bin/bash
# focus the firefox url bar
WID=`xdotool search $1 | head -1`

#DSK=`xdotool get_desktop`

echo 'WID:' $WID
#echo $DSK

if [[ $WID != "" ]]; then
    echo 'Raise window'
    xdotool windowraise  $WID
    xdotool windowactivate $WID
    #xdotool set_desktop_for_window $WID 1
else 
    echo 'Create window'
    gnome-terminal --working-directory='/home/ning/test' -t $1 -e $1
fi 




#xdotool windowactivate --sync $WID
#xdotool key --clearmodifiers ctrl+l


